urls.py
from django.conf import settings
from django.conf.urls.defaults import *

from views import *


from contact import views as contact_view


from django.views.generic.simple import direct_to_template


from django.views.generic import list_detail

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
# Example:
    # (r'^myDjangoStudying/', include('myDjangoStudying.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),


from django.contrib import admin
from django.conf import settings
from db1_django_project.shop.views import image_view
admin.autodiscover()


urlpatterns = patterns('',                       
    (r'^admin/', include(admin.site.urls)),
    (r'^about/$', direct_to_template, {
                                       'template': 'about.html'
                                       }
     ),   
    
    (r'^register/$', register),
    # registration
    (r'^accounts/', include('registration.backends.custom.urls')),    
    (r'^$', direct_to_template,
            { 'template': 'index.html' }, 'index'),
                       
    # database-storage images
    (r'^templates/shop/images/(?P<filename>[a-zA-Z0-9_@./]+)$', image_view),
    
    # static files
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_DOC_ROOT}),
    # contact form
    (r'^contact/', include('django_apps.contact_form.urls')),
    # smart select for select boxes
    (r'^chaining/', include('smart_selects.urls')),
    # parts shop
    (r'^shop/', include('shop.urls')),
    
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^debuginfo/$', debug),
    )

contact/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
Created on Sep 25, 2011

@author: deko
'''

from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, label='Your e-mail address')
    message = forms.CharField(widget=forms.Textarea)
    
    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words!")
        return message

contact/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
Created on Sep 25, 2011

@author: deko
'''

from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response


from db1_django_project.contact.forms import ContactForm

def contact(request):
    if request.method == 'POST':        
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'noreply@example.com'),
                ['siteowner@example.com'],
            )
            return HttpResponseRedirect('/contact/thanks/')
    else:
        form = ContactForm(
            initial={'subject': 'I love your site!'}
        )
    return render_to_response('contact_form.html', {'form': form})

templates/base.html
{% load i18n %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>    
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <META NAME="TITLE" CONTENT="Almaz car - Keretööd ja värvimine">
    <META NAME="DESCRIPTION" CONTENT="Almaz car - Keretööd ja värvimine">
    <META NAME="KEYWORDS" CONTENT="auto,autod,keretööd,keretöö,remont,remond,auto remont,värvimine,varvimine,auto värv">
    <META NAME="ROBOTS" CONTENT="INDEX,FOLLOW">
    <META NAME="REVISIT-AFTER" CONTENT="1 weeks">
    <link rel="shortcut Icon" href="http://127.0.0.1:8000/static/siteimg/favicon.ico" />
    <link rel="stylesheet" href="http://127.0.0.1:8000/static/style.css"/>    

    <title>{% block page_title %}Almaz car{% endblock %}</title>
</head>

<body class="body">

<table width="100%" cellpadding="0" cellspacing="0">
  <tr>
    <td width="70%" align="right" bgcolor="#000000">
    
      <div  id="header">
	    {% block header %}
	    <a href="{% url index %}">{% trans "Home" %}</a> | 

	    {% if user.is_authenticated %}
	    {% trans "Logged in" %}: {{ user.username }} 
	    (<a href="{% url auth_logout %}">{% trans "Log out" %}</a> | 
	    <a href="{% url auth_password_change %}">{% trans "Change password" %}</a>)
	    {% else %}
	    <a href="{% url auth_login %}">{% trans "Log in" %}</a>
	    {% endif %}
	    
	    {% endblock %}
      </div>
    </td>
    <!--<td height="30" bgcolor="#000000">&nbsp;&nbsp;&nbsp;<a href="index_rus.php"><font color="#ffffff">rus</font></a></td>
    -->
  </tr>
  <tr>
    <td align="center" background="http://127.0.0.1:8000/static/siteimg/topbg.jpg"><img src="http://127.0.0.1:8000/static/siteimg/top.jpg"></td>
  </tr>
  <tr>
      <td align="center">
	  {% block link_table %}
	  <table class="link_table_text" cellpadding="00">
	    <tr>
		<td width="130"><a href="/">{% trans "Home" %}</a></td>
		<td width="130"><a href="/">{% trans "Gallery" %}</a></td>
		<td width="150"><a href="/">{% trans "Prices" %}</a></td>
		<td width="150"><a href="/shop">{% trans "Part Shop" %}</a></td>
		<td width="130"><a href="/contact">{% trans "Contact" %}</a></td>
		{% if user.is_authenticated %}
		<td width="130"><a href="/shop/favourites">{% trans "Favourites" %}</a></td>
		<td width="130"><a href="/shop/user_parts" title="Parts for my car model">{% trans "My parts" %}</a></td>
		<td width="130"><a href="/shop/user_profile">{% trans "Profile" %}</a></td> 
		{% endif %}

	    </tr>
	  </table>
	  {% endblock %}
      </td>
  </tr>
  <tr>
      <td height="20"></td>
  </tr>
</table>

<table align="center" width="90%" cellpadding="0" cellspacing="0">
  <tr>
	  <td width="13"><img src="http://127.0.0.1:8000/static/siteimg/table_l.jpg"></td>
	  <td width="" background="http://127.0.0.1:8000/static/siteimg/table_t.jpg">{{ table_heading}}</td>
	  <td width="13"><img src="http://127.0.0.1:8000/static/siteimg/table_r.jpg"></td>
  </tr>
  <tr>
	  <td width="13" background="http://127.0.0.1:8000/static/siteimg/table_lm.jpg"></td>
	  <td>
	      <table class="bodytable">
		  <tr>
		      <td colspan="3" height="20"></td>
		  </tr>	

		  <tr>	 
		      <div id="content">     
			{% block content %}{% endblock %}      
		      </div>
		  </tr>

		  <tr><td colspan="3" height="20"></td></tr>
		  <tr><td colspan="3">
	  
	      </table>
	  </td>
	  <td width="13"background="http://127.0.0.1:8000/static/siteimg/table_rm.jpg"></td>
  </tr>
  <tr>
	  <td width="13"><img src="http://127.0.0.1:8000/static/siteimg/table_lb.jpg"></td>
	  <td width="100%" background="http://127.0.0.1:8000/static/siteimg/table_b.jpg"></td>
	  <td width="13"><img src="http://127.0.0.1:8000/static/siteimg/table_rb.jpg"></td>
  </tr>
</table>


<div>


<table width="100%" cellpadding="0" cellspacing="0">
<tr>
<td height="40" align="center" width="97%"><font size="2" face="Verdana, Arial, Helvetica, sans-serif">&copy 2000-{% now "Y" %} Almaz car O&Uuml;</font></td>

</tr>
</table>
<div>


    

    

    <div id="footer">
        {% block footer %}
        <hr />
        {% endblock %}
    </div>
</body>

</html>

templates/contact_form.html
<html>
<style type="text/css">
    ul.errorlist {
        margin: 0;
        padding: 0;
    }
    .errorlist li {
        background-color: red;
        color: white;
        display: block;
        font-size: 10px;
        margin: 0 0 3px;
        padding: 4px 5px;
    }
</style>
<head>
    <title>Contact us</title>
</head>
<body>
    <h1>Contact us</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
        <div class="field">
            {{ form.subject.errors }}
            <label for="id_subject">Subject:</label>
            {{ form.subject }}
        </div>
        
        <div class="field">
            {{ form.email.errors }}
            <label for="id_email">Your e-mail address:</label>
            {{ form.email }}
        </div>
        
        <div class="field{% if form.message.errors %} errors{% endif %}">
    		{{ form.message.errors}}        	  			
    		<label for="id_message">Message:</label>
    		{{ form.message }}
		</div>
		
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/current_datetime.html
{% extends "base.html" %}

{% block title %}The current time{% endblock %}

{% block content %}
<p>It is now {{ current_date }}.</p>
{% endblock %}

templates/hours_ahead.html
{% extends "base.html" %}

{% block title %}Future time{% endblock %}

{% block content %}
<p>In {{ hour_offset }} hour(s), it will be {{ next_time }}.</p>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<td valign="top" align="left">
	    Kui teie auto kere vajab remonti ja te tahate kiirelt ja kvaliteetselt seda taastada,
	    pöörduge <a href="kontakt.php">meie juurde</a>.<br><br>
	    Hindame kahju suurust ning teeme kahjukäsitlejatele taastamise kalkulatsiooni.<br><br>
		Kasutame järgnevate firmade materialid:<br>
      <a href="http://www2.dupont.com">Du Pont</a>, Sikkens, Lesonal, Roberlo, INDASA, 3M, MIRKA, SOUDAL, Wurth, Presta, Malco, Hagmans
</td>  
<td width="30"></td>
<td valign="top" align="left">
      Meie ettevõte töötab alates 1993 aastast. Oleme parandanud selliseid vigastusi mida keegi teine ei ole suutnud teha.<br>
	<br><b>Auto kere taastamistööd</b> (<a href="hind.php">vaata hinda</a>):<br>
      <img src="http://127.0.0.1:8000/static/siteimg/arrow.gif">Auto kere geomeetriline taastamine.<br>
      <img src="http://127.0.0.1:8000/static/siteimg/arrow.gif">Keevitus ja rihtimistööd.<br>
      <img src="http://127.0.0.1:8000/static/siteimg/arrow.gif">Detailide värvimiseks ettevalmistamine.<br>
      <img src="http://127.0.0.1:8000/static/siteimg/arrow.gif">Vigastatud või B-kategooria elementide konserveerimine.<br>
      <img src="http://127.0.0.1:8000/static/siteimg/arrow.gif">Värvimine, poleerimine.<br>
      <img src="http://127.0.0.1:8000/static/siteimg/arrow.gif">Plastmassdetailide remont.<br>
      <img src="http://127.0.0.1:8000/static/siteimg/arrow.gif">Vedrustus.<br>
      <img src="http://127.0.0.1:8000/static/siteimg/arrow.gif">Elektritööd.
</td>
{% endblock %}

templates/old_base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <h1>My helpful timestamp site</h1>
    {% block content %}{% endblock %}
    {% block footer %}
    <hr>
    <p>Thanks for visiting my site.</p>
    {% endblock %}
</body>
</html>

templates/publisher_list_page.html
{% extends "base.html" %}

{% block content %}
    <h2>Publishers</h2>
    <ul>
        {% for publisher in publisher_list %}
            <li>{{ publisher.name }}</li>
        {% endfor %}
    </ul>
{% endblock %}

templates/search_form.html
<html>
<head>
    <title>Search</title>
</head>
<body>
    {% if errors %}
        <ul>
            {% for error in errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form action="" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
</html>

templates/search_results.html
<p>You searched for: <strong>{{ query }}</strong></p>

{% if books %}
    <p>Found {{ books|length }} book{{ books|pluralize }}.</p>
    <ul>
        {% for book in books %}
        <li>{{ book.title }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No books matched your search criteria.</p>
{% endif %}